"""initial_schema

Revision ID: c6581b221719
Revises: 
Create Date: 2026-01-12 07:30:33.160066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6581b221719'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_key', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('sim_variant', sa.String(length=50), nullable=True),
    sa.Column('lock_state', sa.String(length=50), nullable=True),
    sa.Column('region_variant', sa.String(length=10), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('msrp_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_skus_sku_key'), 'golden_skus', ['sku_key'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.Enum('OFFICIAL', 'VERIFIED', 'MARKETPLACE', 'UNKNOWN', name='merchanttier'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('has_physical_store', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_index(op.f('ix_merchants_normalized_name'), 'merchants', ['normalized_name'], unique=True)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=100), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('tax_refund_value', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('import_duty', sa.Float(), nullable=False),
    sa.Column('final_effective_price', sa.Float(), nullable=False),
    sa.Column('local_price_formatted', sa.String(length=50), nullable=False),
    sa.Column('shop_name', sa.String(length=200), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('sim_type', sa.String(length=100), nullable=True),
    sa.Column('warranty', sa.String(length=200), nullable=True),
    sa.Column('restriction_alert', sa.Text(), nullable=True),
    sa.Column('product_link', sa.Text(), nullable=False),
    sa.Column('merchant_url', sa.Text(), nullable=True),
    sa.Column('immersive_token', sa.String(length=200), nullable=True),
    sa.Column('guide_steps_json', sa.Text(), nullable=True),
    sa.Column('unknown_shipping', sa.Boolean(), nullable=False),
    sa.Column('unknown_refund', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_product_id', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['golden_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_country_code'), 'offers', ['country_code'], unique=False)
    op.create_index(op.f('ix_offers_dedup_key'), 'offers', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_offers_final_effective_price'), 'offers', ['final_effective_price'], unique=False)
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=True)
    op.create_index(op.f('ix_offers_price_usd'), 'offers', ['price_usd'], unique=False)
    op.create_index(op.f('ix_offers_sku_id'), 'offers', ['sku_id'], unique=False)
    op.create_index(op.f('ix_offers_trust_score'), 'offers', ['trust_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_trust_score'), table_name='offers')
    op.drop_index(op.f('ix_offers_sku_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_price_usd'), table_name='offers')
    op.drop_index(op.f('ix_offers_offer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_final_effective_price'), table_name='offers')
    op.drop_index(op.f('ix_offers_dedup_key'), table_name='offers')
    op.drop_index(op.f('ix_offers_country_code'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_merchants_normalized_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_golden_skus_sku_key'), table_name='golden_skus')
    op.drop_table('golden_skus')
    # ### end Alembic commands ###
